"""
Generate dashboard JSON files from the unified feedback data.
Uses Yotpo's built-in sentiment scores and ratings — no external API needed.

Reads: data/processed/unified_feedback.csv
Writes: public/data/sentiment.json (real data)
        public/data/verbatims.json (real quotes)

Note: personas.json and themes.json require Claude API for synthesis.
      Those are generated by analyze.py when the API key is available.
      For now they keep their current AI-generated content which was
      based on the same data sources.
"""
import json
import pandas as pd
from config import PROCESSED_DATA_DIR, PUBLIC_DATA_DIR


def generate_sentiment(df):
    """Generate sentiment.json from real Yotpo sentiment scores and ratings."""

    # Use Yotpo sentiment_score where available, else infer from rating
    df = df.copy()
    df["sentiment_score"] = pd.to_numeric(df["sentiment_score"], errors="coerce")
    df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

    # Fill missing sentiment from rating (1-5 → 0-1 scale)
    mask = df["sentiment_score"].isna() & df["rating"].notna()
    df.loc[mask, "sentiment_score"] = (df.loc[mask, "rating"] - 1) / 4

    # Classify sentiment
    def classify(score):
        if pd.isna(score):
            return "neutral"
        if score >= 0.6:
            return "positive"
        if score <= 0.4:
            return "negative"
        return "neutral"

    df["sentiment"] = df["sentiment_score"].apply(classify)

    scored = df[df["sentiment_score"].notna()]
    overall_score = round(scored["sentiment_score"].mean(), 2) if len(scored) > 0 else 0.5

    total = max(len(df), 1)
    pos = len(df[df["sentiment"] == "positive"])
    neg = len(df[df["sentiment"] == "negative"])
    neu = total - pos - neg

    # By source
    by_source = []
    for source, group in df.groupby("source"):
        g_scored = group[group["sentiment_score"].notna()]
        g_pos = len(group[group["sentiment"] == "positive"])
        g_neg = len(group[group["sentiment"] == "negative"])
        g_neu = len(group) - g_pos - g_neg
        g_total = max(len(group), 1)
        by_source.append({
            "source": source,
            "score": round(g_scored["sentiment_score"].mean(), 2) if len(g_scored) > 0 else 0.5,
            "mentions": len(group),
            "positive": round(g_pos / g_total, 2),
            "neutral": round(g_neu / g_total, 2),
            "negative": round(g_neg / g_total, 2),
        })

    # Sort by mentions descending
    by_source.sort(key=lambda x: -x["mentions"])

    # Over time (monthly)
    df["date_parsed"] = pd.to_datetime(df["date"], errors="coerce")
    df_dated = df[df["date_parsed"].notna()].copy()
    df_dated["month"] = df_dated["date_parsed"].dt.strftime("%Y-%m")
    over_time = []
    for month, group in sorted(df_dated.groupby("month")):
        g_scored = group[group["sentiment_score"].notna()]
        over_time.append({
            "month": month,
            "score": round(g_scored["sentiment_score"].mean(), 2) if len(g_scored) > 0 else 0.5,
            "positive": int(len(group[group["sentiment"] == "positive"])),
            "neutral": int(len(group[group["sentiment"] == "neutral"])),
            "negative": int(len(group[group["sentiment"] == "negative"])),
        })

    # Keep last 12 months
    over_time = over_time[-12:]

    # Top products by review volume (as positive/negative drivers)
    product_sentiment = {}
    product_df = df[df["product_title"].notna() & (df["product_title"] != "")]
    for _, row in product_df.iterrows():
        title = row["product_title"]
        if title not in product_sentiment:
            product_sentiment[title] = {"scores": [], "count": 0}
        if pd.notna(row["sentiment_score"]):
            product_sentiment[title]["scores"].append(row["sentiment_score"])
        product_sentiment[title]["count"] += 1

    sorted_products = sorted(
        [(name, d) for name, d in product_sentiment.items() if len(d["scores"]) >= 10],
        key=lambda x: sum(x[1]["scores"]) / len(x[1]["scores"]) if x[1]["scores"] else 0,
        reverse=True,
    )

    top_positive = [
        {"topic": name, "score": round(sum(d["scores"]) / len(d["scores"]), 2), "mentions": d["count"]}
        for name, d in sorted_products[:5]
    ]
    top_negative = [
        {"topic": name, "score": round(sum(d["scores"]) / len(d["scores"]), 2), "mentions": d["count"]}
        for name, d in sorted_products[-5:]
    ]

    return {
        "overall": {
            "score": overall_score,
            "label": "Positive" if overall_score > 0.6 else "Negative" if overall_score < 0.4 else "Mixed",
            "totalMentions": total,
            "breakdown": {
                "positive": round(pos / total, 2),
                "neutral": round(neu / total, 2),
                "negative": round(neg / total, 2),
            }
        },
        "bySource": by_source,
        "overTime": over_time,
        "topPositiveDrivers": top_positive,
        "topNegativeDrivers": top_negative,
    }


def generate_verbatims(df):
    """Select the most interesting real customer quotes for the verbatim browser."""

    df = df.copy()
    df["sentiment_score"] = pd.to_numeric(df["sentiment_score"], errors="coerce")
    df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
    mask = df["sentiment_score"].isna() & df["rating"].notna()
    df.loc[mask, "sentiment_score"] = (df.loc[mask, "rating"] - 1) / 4
    df["text_len"] = df["text"].astype(str).str.len()

    def classify(score):
        if pd.isna(score):
            return "neutral"
        if score >= 0.6:
            return "positive"
        if score <= 0.4:
            return "negative"
        return "mixed"

    df["sentiment"] = df["sentiment_score"].apply(classify)

    # Select diverse, interesting quotes
    verbatims = []

    # Top positive (high score, decent length)
    pos = df[(df["sentiment_score"] > 0.8) & (df["text_len"] > 50) & (df["text_len"] < 500)]
    for _, row in pos.sample(min(12, len(pos)), random_state=42).iterrows():
        verbatims.append(row)

    # Top negative (low score, decent length)
    neg = df[(df["sentiment_score"] < 0.4) & (df["text_len"] > 50) & (df["text_len"] < 500)]
    for _, row in neg.sample(min(8, len(neg)), random_state=42).iterrows():
        verbatims.append(row)

    # Mixed / interesting (mid score, longer = more detailed)
    mid = df[(df["sentiment_score"] >= 0.4) & (df["sentiment_score"] <= 0.8) & (df["text_len"] > 80)]
    for _, row in mid.sample(min(5, len(mid)), random_state=42).iterrows():
        verbatims.append(row)

    results = []
    for i, row in enumerate(verbatims):
        results.append({
            "id": i + 1,
            "text": str(row["text"])[:400],
            "source": row["source"],
            "sentiment": row["sentiment"],
            "score": round(row["sentiment_score"], 2) if pd.notna(row["sentiment_score"]) else 0.5,
            "theme": "",  # Would need NLP to assign
            "persona": "",  # Would need NLP to assign
            "date": str(row.get("date", ""))[:10],
        })

    return results


def run():
    print("=== Dashboard JSON Generation ===\n")

    unified_path = PROCESSED_DATA_DIR / "unified_feedback.csv"
    if not unified_path.exists():
        print("❌ No unified data found. Run ingest.py first.")
        return

    df = pd.read_csv(unified_path, low_memory=False)
    print(f"Loaded {len(df):,} records\n")

    # Sentiment
    print("Generating sentiment.json...")
    sentiment = generate_sentiment(df)
    with open(PUBLIC_DATA_DIR / "sentiment.json", "w") as f:
        json.dump(sentiment, f, indent=2)
    print(f"  ✅ Overall score: {sentiment['overall']['score']}")
    print(f"     {sentiment['overall']['breakdown']}")
    print(f"     {len(sentiment['overTime'])} months of data")
    print(f"     {len(sentiment['bySource'])} sources\n")

    # Verbatims
    print("Generating verbatims.json...")
    verbatims = generate_verbatims(df)
    with open(PUBLIC_DATA_DIR / "verbatims.json", "w") as f:
        json.dump(verbatims, f, indent=2)
    print(f"  ✅ {len(verbatims)} verbatims selected\n")

    print("✅ Dashboard JSONs updated from real data!")
    print("   sentiment.json — real Yotpo sentiment scores")
    print("   verbatims.json — real customer quotes")
    print("   fairing.json — real Fairing survey aggregations (from ingest.py)")
    print("   personas.json — AI-generated (update with analyze.py when API key is set)")
    print("   themes.json — AI-generated (update with analyze.py when API key is set)")


if __name__ == "__main__":
    run()
